### ISSUE TITLE
Husky, ESLint e Prettier

### ISSUE THREAD

**Issue by irwinschmitt** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil#165]

**Comment by yudi-azvd** [comment]
Issue moved to [UnBArqDsw2022-1/2022.1_G4_FluxoAgil-web #15](https://github.com/UnBArqDsw2022-1/2022.1_G4_FluxoAgil-web/issues/15) via [**ZenHub**](https://www.zenhub.com/)
